### ISSUE TITLE
Errors when train some of the model_spec

### ISSUE THREAD

**Issue by longerHost** [romulus0914/NASBench-PyTorch#4]
Hi @gabrielasuchopar , I found there are plenty of specs that will crash the program. I try to find out a bunch of top-performed models, basically, I iterate through the dataset and keep the `specs` which `acc > 94.4%` at epoch 108 and I try to train these models with the script to get the full training footprint and I found all of these models will crash the program and throw the error, I put a screenshot and the error message here below.

![937ed5c9ba440e55137d145702cc909](https://user-images.githubusercontent.com/8159957/194161466-135c471d-69d5-4bf5-953c-0296a8cce527.png)

```
Traceback (most recent call last):
  File "my_train_script.py", line 277, in <module>
    result = train(net, train_loader, loss=criterion, optimizer=optimizer, scheduler=scheduler, grad_clip=args.grad_clip,
  File "/home/xiaolongm/nasbench101-training/NASBench-PyTorch/nasbench_pytorch/trainer.py", line 76, in train
    curr_loss.backward()
  File "/soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 512, 8, 8]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

Here is the list of some models I put here that will help easy to use:

```
def Load_tops_matix_and_ops():
    matrix_list = []
    operations_list = []

    #test_accuracy is 94.49118375778198
    matrix0 = [[0, 1, 0, 0, 1, 1],
    [0, 0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0]]
    operations0 = ['input', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'output']

    matrix_list.append(matrix0)
    operations_list.append(operations0)

    # test_accuracy is 94.47115659713745
    matrix1 = [[0, 1, 1, 1, 1],
    [0, 0, 1, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0]]  
    operations1 = ['input', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'output']

    matrix_list.append(matrix1)
    operations_list.append(operations1)

    # test_accuracy is 94.46113705635071
    matrix2 = [[0, 1, 1, 0, 0, 1, 1],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0]]
    operations2 = ['input', 'maxpool3x3', 'conv3x3-bn-relu', 'maxpool3x3', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'output']
    matrix_list.append(matrix2)
    operations_list.append(operations2)

    #test_accuracy is 94.55128312110901
    matrix3 = [[0, 1, 1, 0, 1, 1],
    [0, 0, 1, 1, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0]]
    operations3 = ['input', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'output']

    matrix_list.append(matrix3)
    operations_list.append(operations3)

    # 0.9515224099159241
    matrix4 = [[0, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0]]
    operations4 =  ['input', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'output']
    matrix_list.append(matrix4)
    operations_list.append(operations4)

    # 0.9487179517745972
    matrix5 = [[0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0]]
    operations5 = ['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'output']
    matrix_list.append(matrix5)
    operations_list.append(operations5)

    # 94.43109035491943
    matrix6 = [[0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]]
    operations6 = ['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'output']
    matrix_list.append(matrix6)
    operations_list.append(operations6)

    # 0.9463140964508057
    matrix7 = [[0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0]]
    operations7 = ['input', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'conv1x1-bn-relu', 'output']
    matrix_list.append(matrix7)
    operations_list.append(operations7)

    # 0.9479166865348816
    matrix8 = [[0, 1, 1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0]]
    operations8 = ['input', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'output']
    
    matrix_list.append(matrix8)
    operations_list.append(operations8)

    return matrix_list, operations_list
```

You might try to train these models, it should be easy to duplicate the error.

**Comment by gabikadlecova** [comment]
Hi @longerHost,
thank you for submitting the issue. The problem should be fixed now, the new version is uploaded both here and on pypi. I'm closing the issue, if the problem persists for you, I will reopen it.

**Comment by longerHost** [comment]
Thanks for the prompt move, works well now.
